name: Build Electron App

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # Trigger on tags like v1.0.0
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
        
      - name: Install Electron dependencies
        working-directory: electron
        run: npm install

      - name: Build Electron App
        working-directory: electron
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip the application
        working-directory: electron/dist
        run: Compress-Archive -Path "Thermodynamic Instability Dashboard-win32-x64" -DestinationPath "Thermodynamic-Instability-Windows-x64.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: electron/dist/Thermodynamic-Instability-Windows-x64.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: electron/dist/Thermodynamic-Instability-Windows-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
